name: coin_miner
description: COIN MINER Android app
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.5.3
  google_mobile_ads: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
